name: Android Build

on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - uses: gradle/gradle-build-action@v2.4.2
        with:
          gradle-home-cache-cleanup: true

      - name: Build Release Apk with Gradle
        run: ./gradlew assembleRelease

      - name: Build Release bundle with Gradle
        run: ./gradlew bundleRelease

      - name: Upload a Build Artifact (APK)
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: app/build/outputs/apk/release/app-release.apk

      - name: Upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: trusted-testers
          file: app/build/outputs/apk/release/app-release.apk

      - name: Upload to playstore internal release
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.PLAY_CONSOLE_SERVICE_ACCOUNT }}
          packageName: com.peterchege.blogger
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          track: internal
          whatsNewDirectory: distribution/whatsnew
          changesNotSentForReview: true